# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Battle2DServer.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14\x42\x61ttle2DServer.proto\";\n\nPlayerData\x12\r\n\x05round\x18\x01 \x01(\x05\x12\x1e\n\x16serialized_player_data\x18\x02 \x01(\x0c\"\x1c\n\x0bLoadRequest\x12\r\n\x05round\x18\x01 \x01(\x05\"\x0e\n\x0cSaveResponse2d\n\x0b\x44\x61taStorage\x12*\n\nSavePlayer\x12\x0b.PlayerData\x1a\r.SaveResponse\"\x00\x12)\n\nLoadPlayer\x12\x0c.LoadRequest\x1a\x0b.PlayerData\"\x00\x42\x11\xaa\x02\x0eGrpcNetworkingb\x06proto3')



_PLAYERDATA = DESCRIPTOR.message_types_by_name['PlayerData']
_LOADREQUEST = DESCRIPTOR.message_types_by_name['LoadRequest']
_SAVERESPONSE = DESCRIPTOR.message_types_by_name['SaveResponse']
PlayerData = _reflection.GeneratedProtocolMessageType('PlayerData', (_message.Message,), {
  'DESCRIPTOR' : _PLAYERDATA,
  '__module__' : 'Battle2DServer_pb2'
  # @@protoc_insertion_point(class_scope:PlayerData)
  })
_sym_db.RegisterMessage(PlayerData)

LoadRequest = _reflection.GeneratedProtocolMessageType('LoadRequest', (_message.Message,), {
  'DESCRIPTOR' : _LOADREQUEST,
  '__module__' : 'Battle2DServer_pb2'
  # @@protoc_insertion_point(class_scope:LoadRequest)
  })
_sym_db.RegisterMessage(LoadRequest)

SaveResponse = _reflection.GeneratedProtocolMessageType('SaveResponse', (_message.Message,), {
  'DESCRIPTOR' : _SAVERESPONSE,
  '__module__' : 'Battle2DServer_pb2'
  # @@protoc_insertion_point(class_scope:SaveResponse)
  })
_sym_db.RegisterMessage(SaveResponse)

_DATASTORAGE = DESCRIPTOR.services_by_name['DataStorage']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\252\002\016GrpcNetworking'
  _PLAYERDATA._serialized_start=24
  _PLAYERDATA._serialized_end=83
  _LOADREQUEST._serialized_start=85
  _LOADREQUEST._serialized_end=113
  _SAVERESPONSE._serialized_start=115
  _SAVERESPONSE._serialized_end=129
  _DATASTORAGE._serialized_start=131
  _DATASTORAGE._serialized_end=231
# @@protoc_insertion_point(module_scope)
